export const GET_PRODUCTS = 'GET_PRODUCTS';
export const ADD_BASKET_ITEM = 'ADD_BASKET_ITEM';
export const UPDATE_BASKET_ITEM = 'UPDATE_BASKET_ITEM';
export const DELETE_BASKET_ITEM = 'DELETE_BASKET_ITEM';
